# -*- coding: utf-8 -*-
"""90-day Instagram + performance calendar data for DegreeComplete.in.
Every day: mode (ORGANIC / PERFORMANCE AD), format, course, hook, post idea, caption body, CTA, image scene, landing page, KPIs.
Facts marked (SOURCE) come from the owner's July-2026 fee sheets / admission master; nothing else is claimed as data.
"""

MASTER_PROMPT = ("Premium Indian education technology advertising creative, sophisticated deep navy and gold brand palette, white negative space, "
                 "elegant academic visual language, realistic Indian student or working professional, premium corporate photography, cinematic soft lighting, "
                 "clean composition, modern editorial advertising style, high trust, aspirational but realistic, minimal clutter, luxury education brand aesthetic, "
                 "sharp subject, professional typography area, {ratio} composition, consistent navy-gold-white branding, no fake logos, no unnecessary text, no watermark. ")

GEO_PRIMARY = "Mumbai, Thane, Navi Mumbai, Pune, Nagpur, Nashik, Chhatrapati Sambhajinagar"
GEO_ORGANIC = "Maharashtra-first; India-wide reach welcome (Online programs)"
GEO_SCALE = "Maharashtra primary + expansion test: Delhi NCR, Bengaluru, Hyderabad, Ahmedabad, Jaipur, Lucknow (Online programs only; check ODL jurisdiction separately)"
GEO_RT = "Retargeting audiences only (all locations where the audience exists)"

TAGS = {
    "gen": "#DegreeComplete #OnlineEducation #DistanceLearning #OnlineDegree #StudyFromHome #HigherEducationIndia #CompleteYourEducation #MumbaiEducation #CareerGrowth #UGCDEB",
    "mba": "#OnlineMBA #DistanceMBA #MBAWhileWorking #MBAIndia #WorkingProfessionals #CareerUpgrade #DegreeComplete #OnlineEducation #MBAAdmission #StudyWhileWorking",
    "bba": "#OnlineBBA #BBA #After12th #12thPass #GraduationFromHome #OnlineDegree #DegreeComplete #ManagementDegree #CompleteYourGraduation #StudyFromHome",
    "bca": "#OnlineBCA #BCA #ITCareer #After12th #TechCareer #ComputerApplications #DegreeComplete #OnlineDegree #CodingCareer #12thPass",
    "mca": "#OnlineMCA #MCA #TechUpgrade #AIandML #DataScience #ITCareer #DegreeComplete #OnlineEducation #CareerSwitch #Graduates",
    "grad": "#CompleteYourGraduation #OnlineBA #OnlineBCom #GraduationFromHome #AcademicGap #12thPass #DegreeComplete #DistanceEducation #SecondChance #StudyWhileWorking",
    "trust": "#DegreeComplete #EducationGuidance #OnlineEducation #TransparentFees #StudentFirst #MumbaiInstitute #DistanceLearning #UGCDEB #VerifyBeforeYouEnrol #HigherEducation",
}

# ----------------------------------------------------------------------------------------------
# Helper to build a day entry compactly.
# ----------------------------------------------------------------------------------------------
def d(day, phase, mode, fmt, course, category, objective, funnel, audience, age, geo, hook, idea, body, cta, dm, tags, scene, campaign, lp, kpi1, kpi2, purpose, cls, ratio="4:5 Instagram portrait", story=None, trust=None):
    return dict(day=day, phase=phase, mode=mode, fmt=fmt, course=course, category=category, objective=objective, funnel=funnel, audience=audience, age=age, geo=geo,
                hook=hook, idea=idea, body=body, cta=cta, dm=dm, tags=TAGS[tags], scene=scene, campaign=campaign, lp=lp, kpi1=kpi1, kpi2=kpi2, purpose=purpose, cls=cls, ratio=ratio, story=story,
                trust=trust or "Guidance is based on your qualification and each university's current program eligibility. Fees are shown exactly as published by the university.")

P1, P2, P3, P4, P5, P6 = "Phase 1 · Brand & trust", "Phase 2 · Course education", "Phase 3 · University, fee & comparison", "Phase 4 · Problem-solving & lead magnets", "Phase 5 · Performance scale", "Phase 6 · Retargeting & conversion"
O, PA = "ORGANIC", "PERFORMANCE AD"
LP = dict(home="/", find="/find-course", mba="/online-mba", bba="/online-bba", bca="/online-bca", mca="/online-mca", ba="/online-ba", bcom="/online-bcom", grad="/online-degree-after-12th (alias /graduation)", cmp="/compare", uni="/universities", docs="/documents-required", elig="/eligibility (form → /find-course)", process="/admission-process")

DAYS = [
# ───────────────────────── PHASE 1 (Days 1–15): Brand introduction + trust ─────────────────────────
d(1, P1, O, "Static", "General", "Brand", "Awareness / Followers", "TOFU", "All segments", "18–40", GEO_ORGANIC,
  "Ek platform, 26+ universities, 300+ programs — aur zero confusion.",
  "Brand launch post: the seal, the promise and what the platform does in one line each.",
  "DegreeComplete.in is the student platform of Mumbai Institute for Online & Distance Learning. Here you can explore online and distance degree programs from partner universities, compare courses and fees, check eligibility and apply with guidance. We are not a university — we help you choose the right one and stay with you till your degree.",
  "Follow @degreecomplete.in and save this post.", "HELLO", "trust",
  "Institutional seal centred on white with a thin gold rule beneath; below, a confident young Indian woman and a man in office wear looking at a laptop together, navy background band at bottom for headline.",
  "—", LP["home"], "Followers", "Profile visits", ["REACH", "FOLLOWERS"], "FOLLOWER", story="Welcome poll: “आप क्या करना चाहते हैं?” Graduation complete / MBA / Career switch / Not sure"),
d(2, P1, O, "Reel", "General", "Trust", "Awareness", "TOFU", "12th pass + graduates", "18–34", GEO_ORGANIC,
  "Online degree लेने से पहले ये 3 चीज़ें verify करो.",
  "15-second reel, text-on-screen: 1) University + program recognition for your session 2) Fee breakup in writing 3) Who supports you after admission.",
  "Ek galat university choice saalon ka nuksaan kar sakti hai. Enrol karne se pehle university aur program ki current recognition/entitlement apne academic session ke liye verify karo, fee ka pura breakup likhit mein lo, aur poocho ki admission ke baad support kaun dega. Yahi teen cheezein hum har student ke liye pehle check karte hain.",
  "Save this reel. Share it with someone who is choosing a course.", "VERIFY", "trust",
  "Vertical: close-up of hands holding a phone showing a checklist, blurred study desk behind, navy and gold text card overlay area on top third.",
  "—", LP["elig"], "Reach", "Saves", ["REACH", "FOLLOWERS"], "FOLLOWER", ratio="9:16 vertical Reel"),
d(3, P1, O, "Carousel", "General", "Online vs Distance", "Engagement / Followers", "TOFU", "All segments", "18–40", GEO_ORGANIC,
  "Online और Distance — actual difference क्या है?",
  "7-slide carousel: mode of classes, exams, who it suits, geographic rules differ (ODL has jurisdiction rules), same degree value when recognised, how to decide.",
  "Online mode: classes, material and exams on an LMS, mostly remote-proctored. Distance (ODL): printed/online material with centre-based exams at many universities, and territorial rules can apply. Dono mein degree university hi deti hai. Aapke liye kaunsa sahi hai, yeh aapki location, schedule aur course par depend karta hai.",
  "Comment “ONLINE” or “DISTANCE” and we will tell you what fits your situation.", "MODE", "gen",
  "Split composition: left half a student on a laptop at home, right half a student with printed books; navy divider with gold labels ONLINE and DISTANCE.",
  "—", LP["uni"], "Saves", "Comments", ["FOLLOWERS", "ENGAGEMENT"], "FOLLOWER"),
# Days 4–7: FIRST-7-DAY PAID TEST LAYER (4 lead-generation creatives, one per priority course)
d(4, P1, PA, "Lead Ad (Reel)", "MBA", "MBA · Working professional", "Lead", "MOFU", "Graduates in jobs", "24–34", GEO_PRIMARY,
  "Job के साथ MBA — बिना career रोके.",
  "TEST CREATIVE 1 of 4. 20-sec vertical: professional at desk → phone shows program list → “Check eligibility in 2 minutes”. Instant form with qualification + city + course.",
  "Working professional ho aur MBA karna chahte ho? Partner universities ke Online MBA programs mein classes recorded/live online hoti hain, exams online, aur most universities mein entrance exam nahi hai (SOURCE: admission master). Fees ₹62,000 se ₹3 lakh tak range karti hain, university ke hisaab se (SOURCE, verify current). Pehle apni eligibility check karo, phir decide karo.",
  "Check My Eligibility", "MBA", "mba",
  "Vertical: 28-year-old Indian professional in a modern office at dusk, laptop open, phone in hand, calm focused expression; navy overlay band with gold accent line.",
  "Leads (instant form) — Test A", LP["mba"], "Cost per qualified lead", "CTR", ["LEAD"], "LEAD", ratio="9:16 vertical Reel"),
d(5, P1, PA, "Lead Ad (Static)", "BBA", "BBA · 12th pass", "Lead", "MOFU", "12th pass, not in college", "18–24", GEO_PRIMARY,
  "12th के बाद graduation छूट गई? Online BBA घर से.",
  "TEST CREATIVE 2 of 4. Static 4:5 with three facts: 3 years, no entrance exam, study from home. Instant form.",
  "12th ke baad college join nahi kar paaye ya chhod di? Online BBA se graduation ghar se complete karo — 3 saal ka UGC-recognised degree program partner universities ke saath, most mein bina entrance exam (SOURCE). Documents aur eligibility hum pehle check karte hain, phir application.",
  "Check My Eligibility", "BBA", "bba",
  "Young Indian man, 19–20, at a small home study table with a laptop, sunlight from window, hopeful expression; clean white wall, navy headline block.",
  "Leads (instant form) — Test B", LP["bba"], "Cost per qualified lead", "CTR", ["LEAD"], "LEAD"),
d(6, P1, PA, "Lead Ad (Static)", "BCA", "BCA · Tech career", "Lead", "MOFU", "12th pass, tech-inclined", "18–24", GEO_PRIMARY,
  "IT career चाहिए? 12th के बाद Online BCA.",
  "TEST CREATIVE 3 of 4. Static with specialization chips (AI, Data Science, Cloud, Cyber Security — SOURCE: partner catalogue).",
  "Coding, data ya cyber security mein career banana hai? Online BCA 12th ke baad shuru ho sakta hai, aur partner universities AI, Data Science, Cloud aur Cyber Security jaise specializations offer karti hain (SOURCE). Kuch universities 10+2 mein Maths prefer karti hain — hum pehle check karte hain aap eligible ho ya nahi.",
  "Check My Eligibility", "BCA", "bca",
  "Indian teenager coding on a laptop, second screen with abstract code (no readable text), dark navy desk setup with a single warm lamp; gold accent stripe.",
  "Leads (instant form) — Test C", LP["bca"], "Cost per qualified lead", "CTR", ["LEAD"], "LEAD"),
d(7, P1, PA, "Lead Ad (Reel)", "BA / B.Com", "Graduation completion", "Lead", "MOFU", "Academic gap, working", "21–34", GEO_PRIMARY,
  "Graduation बीच में छूट गई? अब घर से complete करो.",
  "TEST CREATIVE 4 of 4. 15-sec reel: “Job, family, responsibilities — graduation reh gayi. Ab Online BA / B.Com ghar se. Eligibility check free.”",
  "Kaam, ghar ya paise ki wajah se graduation adhuri reh gayi? Online BA aur B.Com se aap ghar se graduate ho sakte ho — 12th pass eligibility, most universities mein bina entrance exam (SOURCE). Aapki academic history ke hisaab se hum batayenge kaunsa option open hai. Har case same nahi hota, isliye pehle eligibility check.",
  "Check My Eligibility", "GRADUATION", "grad",
  "Vertical: Indian woman, late 20s, in a kitchen-side study corner at night with a laptop, child's drawing on the wall; warm but composed lighting; navy caption zone.",
  "Leads (instant form) — Test D", LP["grad"], "Cost per qualified lead", "Qualified lead rate", ["LEAD"], "LEAD", ratio="9:16 vertical Reel"),
d(8, P1, O, "Carousel", "General", "Who we are", "Trust / Followers", "TOFU", "All segments", "18–40", GEO_ORGANIC,
  "हम university नहीं हैं — और यही हमारी strength है.",
  "6 slides: what we are (guidance + admission support), what we are not (not a university, no degree from us), what you get (compare, eligibility, documents, tracking), what we never do (guarantee jobs/admission).",
  "Mumbai Institute for Online & Distance Learning ek guidance aur admission-support platform hai. Degree university deti hai; hum aapko sahi university aur course chunne, documents verify karne, apply karne aur degree tak track karne mein madad karte hain. Hum job, salary ya admission ki guarantee nahi dete — hum sach batate hain.",
  "Follow for honest education guidance.", "HELLO", "trust",
  "Counsellor (Indian woman, 30s, formal) explaining on a tablet to a student across a clean white desk; seal subtly on the wall; navy-gold typography zone.",
  "—", LP["home"], "Followers", "Saves", ["FOLLOWERS", "REACH"], "TRUST"),
d(9, P1, O, "Reel", "General", "Career", "Awareness / Followers", "TOFU", "Working, 12th pass", "21–34", GEO_ORGANIC,
  "3 reasons your incomplete graduation is holding your career back.",
  "Talking-head style reel with subtitles: eligibility for promotions/govt exams, salary bands often tied to degree, switching companies needs a degree on paper.",
  "Kai companies aur government exams mein graduation minimum eligibility hai. Bina degree ke promotion rukti hai, naye offers kam aate hain, aur higher studies (MBA/MCA) ke darwaze band rehte hain. Achhi baat: graduation ab ghar se, job ke saath complete ho sakti hai.",
  "Save and send this to a friend who needs it.", "GRADUATION", "grad",
  "Vertical: confident Indian man, 30, in a city commute setting (train window), subtle motion blur, thoughtful; navy subtitle band.",
  "—", LP["grad"], "Reach", "Shares", ["REACH", "FOLLOWERS"], "FOLLOWER", ratio="9:16 vertical Reel"),
d(10, P1, O, "Static", "General", "Trust · Fees", "Trust", "TOFU", "All", "18–40", GEO_ORGANIC,
  "Fees छिपाकर नहीं, पूरी लिखकर दिखाते हैं.",
  "Screenshot-style graphic of a program fee card: registration, exam, tuition, plans — with “exactly as published by the university”.",
  "Har program page par registration fee, exam fee, tuition aur payment plans alag-alag dikhte hain — jaise university ne publish kiya hai. Koi hidden charge nahi, aur fees aap seedha university ko pay karte ho. Pehle se pata ho toh decision aasaan hota hai.",
  "Explore Courses at DegreeComplete.in", "FEES", "trust",
  "Flat-lay of a printed fee breakup sheet, pen and phone on a white desk; gold paperclip; navy header block.",
  "—", LP["uni"], "Link clicks", "Profile visits", ["WEBSITE TRAFFIC", "REACH"], "TRUST"),
d(11, P1, O, "Carousel", "General", "Myth vs Fact", "Engagement / Followers", "TOFU", "All", "18–40", GEO_ORGANIC,
  "Myth vs Fact: Online degree की value कम होती है?",
  "5 myths: online degree is 'less', anyone can enrol from anywhere in ODL, you get a degree without exams, all universities are same, an agent can 'fix' eligibility. Each with a careful fact.",
  "Fact: recognised online/ODL degrees university se hi milti hain, exams hoti hain, aur eligibility rules real hain. ODL mein territorial rules apply ho sakte hain; online mein bhi university ke rules chalte hain. Koi bhi 'eligibility fix' nahi kar sakta — sirf sahi course match kiya ja sakta hai.",
  "Comment MYTH to get the full guide.", "MYTH", "trust",
  "Two-tone card: left navy 'MYTH' with a crossed icon, right white 'FACT' with a gold tick; Indian student silhouette reading.",
  "—", LP["elig"], "Saves", "Comments", ["ENGAGEMENT", "FOLLOWERS"], "FOLLOWER"),
d(12, P1, O, "Reel", "General", "Behind the scenes", "Trust", "TOFU", "All", "18–40", GEO_ORGANIC,
  "Ek enquiry ke baad actually kya hota hai? (Behind the scenes)",
  "Screen-record + voiceover: lead arrives in CRM → counsellor calls → eligibility check → document pre-check → application. No faces needed.",
  "Aapki enquiry aate hi counsellor assign hota hai, qualification aur documents check hote hain, phir program options aur exact fees share hoti hain. Application tab hi jaati hai jab sab verify ho jaaye. Yeh process har student ke liye same hai.",
  "Try it: message GUIDE.", "GUIDE", "trust",
  "Vertical: over-the-shoulder view of a counsellor's desk with laptop CRM (abstract UI), headset, notebook; navy tones.",
  "—", LP["process"], "Reach", "Profile visits", ["REACH", "WHATSAPP"], "TRUST", ratio="9:16 vertical Reel"),
d(13, P1, O, "Static", "General", "Recognition", "Trust", "TOFU", "All", "18–40", GEO_ORGANIC,
  "Enrol करने से पहले recognition verify करो — यहाँ से.",
  "Explainer: what UGC-DEB entitlement means, why it is program + session specific, how to check; we encourage students to verify themselves.",
  "Online/ODL programs ki recognition university, program aur academic session ke hisaab se hoti hai. Enrol karne se pehle apne session ke liye current entitlement verify karo — hum bhi yahi karte hain aur aapko dikhate hain. Blanket claims par bharosa mat karo.",
  "Save this. Ask us: message VERIFY.", "VERIFY", "trust",
  "Magnifying glass over an abstract official document on a navy desk, gold seal-like accent (not a real badge); clean white text area.",
  "—", LP["elig"], "Saves", "DMs", ["ENGAGEMENT", "WHATSAPP"], "TRUST"),
d(14, P1, O, "Carousel", "General", "Course choice", "Followers", "TOFU", "12th pass + graduates", "18–30", GEO_ORGANIC,
  "Course चुनने से पहले ये 5 चीज़ें check करो.",
  "Eligibility, duration (min/max), fee breakup, specializations, support after admission — from the platform's own fields.",
  "1) Eligibility — marks aur subjects 2) Duration — minimum aur maximum time 3) Fee breakup — registration, exam, tuition 4) Specializations — jo aapke career se match karein 5) Support — documents se degree tak kaun saath hai. Yeh paanch cheezein har program page par ek jagah milti hain.",
  "Save this checklist. Explore courses at DegreeComplete.in.", "COURSE", "gen",
  "Notebook checklist with five gold ticks beside a laptop; Indian student's hands; white desk, navy header.",
  "—", LP["find"], "Saves", "Link clicks", ["FOLLOWERS", "WEBSITE TRAFFIC"], "FOLLOWER"),
d(15, P1, O, "Story set + Static", "General", "Community", "Engagement", "TOFU", "All", "18–40", GEO_ORGANIC,
  "आपका सबसे बड़ा confusion क्या है? (हम जवाब देंगे)",
  "Question sticker day: collect real doubts; answer top 5 in a static post the same evening. First-7-day results review internally today.",
  "Course, university, fees, eligibility ya documents — jo bhi confusion hai, bhejo. Aaj hum sabse common 5 sawaalon ke jawab post karenge. Yeh page selling ke liye nahi, sahi decision ke liye hai.",
  "Reply on the story or DM ASK.", "ASK", "gen",
  "Phone mock showing a question sticker on a navy story background with gold accents.",
  "—", LP["home"], "Replies", "Followers", ["ENGAGEMENT", "FOLLOWERS"], "FOLLOWER", ratio="9:16 story", story="Question sticker + 'This or that' polls (Online/Distance, MBA/MCA); share best replies"),

# ───────────────────────── PHASE 2 (Days 16–30): Course education ─────────────────────────
d(16, P2, O, "Carousel", "MBA", "MBA explainer", "Followers / Traffic", "TOFU", "Graduates + working", "21–34", GEO_ORGANIC,
  "Online MBA: कौन कर सकता है, कितना time, क्या मिलेगा?",
  "8 slides: eligibility (bachelor's, ~50%/45% reserved — SOURCE common rules), duration 2 yrs (max 4), semesters, specializations available across partners, no entrance exam at most, what to check.",
  "Online MBA ke liye generally kisi bhi discipline mein bachelor's degree chahiye, minimum 50% (reserved category 45%) — kuch universities work experience ke saath kam marks bhi accept karti hain (SOURCE). Duration 2 saal, maximum 4 saal. Marketing, Finance, HR, Analytics, Operations, Digital Marketing jaise specializations partner universities mein available hain.",
  "Explore Online MBA options.", "MBA", "mba",
  "Indian professional woman, 27, reviewing a printed program brochure at a café table, laptop open; navy-gold slide framing.",
  "—", LP["mba"], "Link clicks", "Saves", ["WEBSITE TRAFFIC", "FOLLOWERS"], "FOLLOWER"),
d(17, P2, O, "Reel", "MBA", "MBA specialization", "Engagement", "TOFU", "Graduates", "21–34", GEO_ORGANIC,
  "MBA specialization कैसे चुनें? 4 सवाल.",
  "Quick reel: current job, target role, numbers vs people, industry demand — map to Finance/Marketing/HR/Analytics/Operations.",
  "Specialization aapke target role se decide karo, trend se nahi. Numbers pasand hain — Finance/Analytics. People aur communication — HR/Marketing. Process aur supply chain — Operations. Confused ho toh dual-specialization options bhi kuch universities mein hain (SOURCE).",
  "Comment your current job and we will suggest 2 options.", "MBA", "mba",
  "Vertical: four floating cards (icons only) around a young Indian professional, navy background, gold highlights.",
  "—", LP["mba"], "Comments", "Reach", ["ENGAGEMENT", "FOLLOWERS"], "FOLLOWER", ratio="9:16 vertical Reel"),
d(18, P2, O, "Carousel", "BBA", "BBA explainer", "Followers / Traffic", "TOFU", "12th pass", "18–24", GEO_ORGANIC,
  "Online BBA after 12th — पूरा picture.",
  "Eligibility 10+2 any stream, pass to 40–50% (SOURCE), 3 years/6 semesters (max 6), specializations (Finance, Marketing, HR, Digital Marketing, Analytics), what it leads to (MBA, entry-level management roles).",
  "12th ke baad kisi bhi stream se BBA ho sakta hai; minimum marks pass se 40–50% tak university par depend karta hai (SOURCE). 3 saal, 6 semester, aur aap MBA ke liye eligible ho jaate ho. Ghar se, job ke saath.",
  "See BBA options and fees.", "BBA", "bba",
  "Two Indian students, 19, on a college-style bench with a laptop, outdoor soft light; navy card overlay.",
  "—", LP["bba"], "Link clicks", "Saves", ["WEBSITE TRAFFIC", "FOLLOWERS"], "FOLLOWER"),
d(19, P2, O, "Reel", "BCA", "BCA vs BBA", "Followers", "TOFU", "12th pass", "18–24", GEO_ORGANIC,
  "BCA vs BBA — कौन सा आपके लिए बेहतर?",
  "Split-screen reel: interests, subjects, careers, next step (MCA vs MBA). Ends with 'both are 3 years, both from home'.",
  "BCA — computers, coding, data, IT career, aage MCA. BBA — business, marketing, finance, management, aage MBA. Dono 3 saal, dono ghar se. Maths pasand hai aur tech mein jaana hai toh BCA; logon aur business ke saath kaam karna hai toh BBA.",
  "Comment BCA or BBA — we will send the eligibility for both.", "BCA", "bca",
  "Vertical split: left navy with code motifs and a young man, right gold with charts and a young woman.",
  "—", LP["bca"], "Reach", "Comments", ["FOLLOWERS", "ENGAGEMENT"], "FOLLOWER", ratio="9:16 vertical Reel"),
d(20, P2, O, "Carousel", "BCA", "BCA explainer", "Traffic", "MOFU", "12th pass", "18–24", GEO_ORGANIC,
  "Online BCA: eligibility, specializations, career.",
  "Eligibility 10+2 any stream, Maths/CS preferred and mandatory at a few (SOURCE), specializations (AI, Data Science, Cloud, Cyber Security, Full-stack), 3 years.",
  "BCA ke liye 10+2 kisi bhi stream se chalta hai, lekin kuch universities Maths/Computer Science 12th mein maangti hain (SOURCE). Partner universities AI & Data Science, Cloud, Cyber Security, Full-Stack jaise specializations offer karti hain. Pehle apna 12th subject batao — hum sahi university match karenge.",
  "Explore BCA programs.", "BCA", "bca",
  "Indian student with a laptop in a library, screen glow, abstract network graphic; navy-gold layout.",
  "—", LP["bca"], "Link clicks", "Saves", ["WEBSITE TRAFFIC"], "LEAD"),
d(21, P2, O, "Carousel", "MCA", "MCA explainer", "Traffic", "MOFU", "Graduates, IT-inclined", "21–30", GEO_ORGANIC,
  "Online MCA — graduate से tech professional.",
  "Eligibility: BCA/B.Sc/B.Tech or any graduate WITH Maths at 10+2 or graduation (SOURCE), 50%/45%, bridge course where allowed; specializations AI&ML, Data Science, Cyber Security, Cloud, Full-stack.",
  "MCA ke liye graduation chahiye aur Maths 10+2 ya graduation level par (SOURCE) — bina Maths ke kuch universities bridge course allow karti hain. 2 saal, AI & ML, Data Science, Cyber Security, Cloud jaise specializations. Non-IT graduate ho? Pehle Maths eligibility check karo.",
  "Check MCA eligibility.", "MCA", "mca",
  "Indian graduate, 24, at a dual-monitor workstation, abstract data visual, navy setting, gold accent line.",
  "—", LP["mca"], "Link clicks", "Leads", ["WEBSITE TRAFFIC", "LEAD"], "LEAD"),
d(22, P2, O, "Reel", "MCA", "Career switch", "Followers", "TOFU", "Non-IT graduates", "22–32", GEO_ORGANIC,
  "Non-IT graduate होकर tech में आना है? पहले ये check करो.",
  "Reel: the one filter (Maths), then the path — MCA with AI/Data specialization, while working.",
  "Commerce ya arts graduate ho aur IT mein switch karna hai? MCA possible hai, lekin sabse pehla filter Maths hai — 10+2 ya graduation mein. Jahan allowed hai wahan bridge course option hota hai (SOURCE). Baaki sab planning ke baad.",
  "Message MCA with your graduation subject.", "MCA", "mca",
  "Vertical: person removing a formal tie at a desk, laptop transitioning to code (abstract); navy mood, gold text area.",
  "—", LP["mca"], "Reach", "DMs", ["REACH", "WHATSAPP"], "FOLLOWER", ratio="9:16 vertical Reel"),
d(23, P2, O, "Carousel", "BA / B.Com", "Graduation completion", "Traffic", "MOFU", "Academic gap", "21–34", GEO_ORGANIC,
  "Graduation complete करने के 5 फायदे (job के साथ).",
  "Eligibility for jobs/govt exams, promotion, higher studies, salary band, confidence — and BA/B.Com online eligibility 12th pass, 3 yrs, no entrance at most.",
  "Job ke saath Online BA ya B.Com se graduation complete ho sakti hai — 12th pass eligibility, 3 saal, most universities mein bina entrance exam (SOURCE). Graduation ke baad promotions, government exams, MBA/MA aur naye offers ke raste khulte hain.",
  "See BA & B.Com options.", "GRADUATION", "grad",
  "Indian man, 30, in a security-guard/retail uniform jacket over a shirt, studying at night on a phone; respectful, hopeful; navy layout.",
  "—", LP["grad"], "Link clicks", "Leads", ["WEBSITE TRAFFIC", "LEAD"], "LEAD"),
d(24, P2, O, "Static", "BA / B.Com", "Eligibility", "Engagement", "TOFU", "12th pass", "18–30", GEO_ORGANIC,
  "12th में कम marks? फिर भी graduation possible है.",
  "Fact card: many partner universities accept pass marks for BA/B.Com; some ask 40–50% — check by university (SOURCE).",
  "BA/B.Com ke liye kai partner universities mein sirf 12th pass chahiye; kuch 40–50% maangti hain (SOURCE). Aapke marks ke hisaab se kaunsi universities open hain, yeh hum 5 minute mein bata sakte hain.",
  "Message GRADUATION with your 12th percentage.", "GRADUATION", "grad",
  "Close-up of a marksheet (blurred numbers) and a hopeful young Indian woman; white background, navy band.",
  "—", LP["grad"], "DMs", "Saves", ["WHATSAPP", "ENGAGEMENT"], "LEAD"),
d(25, P2, O, "Reel", "MBA", "Student mistakes", "Followers", "TOFU", "Graduates + working", "21–34", GEO_ORGANIC,
  "Online MBA लेने से पहले ये 5 mistakes मत करना.",
  "Reel: choosing by ad not eligibility, ignoring exam fee, not asking about max duration, not checking specialization list, paying without written fee.",
  "1) Sirf ad dekh kar choose karna 2) Exam aur registration fee ignore karna 3) Maximum duration na poochna 4) Specialization list na dekhna 5) Bina likhit fee ke pay karna. Yeh paanch galtiyan rokna hi hamara kaam hai.",
  "Save this. Explore MBA with full fee breakup.", "MBA", "mba",
  "Vertical: Indian professional facepalm-lite humour, then confident; navy background with five gold numbered chips.",
  "—", LP["mba"], "Reach", "Saves", ["REACH", "FOLLOWERS"], "FOLLOWER", ratio="9:16 vertical Reel"),
d(26, P2, O, "Carousel", "MA / M.Com / M.Sc", "PG explainers", "Traffic", "MOFU", "Graduates", "21–34", GEO_ORGANIC,
  "MA, M.Com, M.Sc online — किसके लिए कौन सा?",
  "MA (English, Economics, Political Science, Sociology, JMC) any graduate; M.Com commerce/any graduate at several; M.Sc needs relevant B.Sc subject (SOURCE).",
  "MA ke liye generally koi bhi graduate eligible hai; M.Com ke liye commerce/management background preferred (kai universities any graduate lete hain); M.Sc Maths/Physics/Data Science ke liye relevant subject B.Sc mein chahiye (SOURCE). 2 saal, ghar se, teaching/UPSC/research ke liye useful.",
  "Explore MA, M.Com and M.Sc programs.", "PG", "gen",
  "Three Indian graduates with different props (book, ledger, lab notebook) on a white set; navy-gold framing.",
  "—", LP["find"], "Link clicks", "Saves", ["WEBSITE TRAFFIC"], "FOLLOWER"),
d(27, P2, O, "Reel", "General", "Working professional", "Followers", "TOFU", "Working", "24–40", GEO_ORGANIC,
  "Job के साथ पढ़ाई — एक हफ्ते का realistic schedule.",
  "Reel: 6–8 hrs/week split across recorded lectures, weekend live, assignments; honest about effort.",
  "Online degree ka matlab zero effort nahi hai. Realistic plan: hafte mein 6–8 ghante — recorded lectures commute mein, weekend par live session, assignment ek shaam. Discipline aap laate ho, structure university deti hai, follow-up hum karte hain.",
  "Save this schedule.", "PLAN", "gen",
  "Vertical: weekly planner on a desk with a coffee, phone showing a lecture (abstract), morning light; navy-gold overlay.",
  "—", LP["find"], "Saves", "Reach", ["FOLLOWERS", "REACH"], "FOLLOWER", ratio="9:16 vertical Reel"),
d(28, P2, O, "Static", "MBA", "Executive / WX", "Traffic", "MOFU", "Working 3+ yrs", "26–40", GEO_ORGANIC,
  "3+ years experience? Executive MBA options भी हैं.",
  "Card: Executive/WX formats need work experience (2–3 yrs typical), interview/profile screening may apply (SOURCE).",
  "Working executives ke liye Executive MBA / MBA (WX) formats hain jinme minimum work experience chahiye (usually 2–3 saal) aur profile screening ho sakti hai (SOURCE). Regular Online MBA se fees aur format alag hote hain. Aapke profile par kya fit hai, yeh ek call mein clear ho jaata hai.",
  "Compare Executive vs Online MBA — message EXEC.", "EXEC", "mba",
  "Senior Indian professional, 36, in a glass meeting room with a tablet; navy-gold editorial style.",
  "—", LP["mba"], "DMs", "Link clicks", ["WHATSAPP", "WEBSITE TRAFFIC"], "LEAD"),
d(29, P2, O, "Carousel", "General", "Duration rules", "Followers", "TOFU", "All", "18–40", GEO_ORGANIC,
  "Kitna time milta hai degree complete karne ke liye? (UGC rule)",
  "UG min 3 / max 6 yrs; PG min 2 / max 4; Diploma 1/2; Certificate 6m/1yr (SOURCE: admission master). Complete at own pace within max window.",
  "UG: minimum 3 saal, maximum 6. PG: minimum 2, maximum 4. Diploma: 1/2. Certificate: 6 mahine/1 saal (SOURCE). Yani job ya family ki wajah se ek semester slow ho gaye toh degree nahi jaati — maximum window ke andar complete karo.",
  "Save this. Share with a working friend.", "TIME", "gen",
  "Hourglass with gold sand beside a graduation cap on a white surface; navy header.",
  "—", LP["process"], "Saves", "Shares", ["FOLLOWERS", "ENGAGEMENT"], "FOLLOWER"),
d(30, P2, O, "Story set + Reel", "General", "Course finder", "Engagement / Lead", "MOFU", "All", "18–40", GEO_ORGANIC,
  "5 सवाल, 2 minute — आपका right course.",
  "Story quiz funnel (qualification → goal → mode → budget) ending in link to /find-course; reel demo of the finder.",
  "Qualification, kya padhna hai, Online ya Distance, budget aur goal — bas 5 sawaal, aur aapko sirf wahi programs dikhte hain jinke liye aap eligible ho. Phir ek advisor exact eligibility aur current fee confirm karta hai.",
  "Find My Course — link in bio.", "COURSE", "gen",
  "Vertical: phone-in-hand screen recording of the course finder (abstract UI), navy background, gold progress dots.",
  "—", LP["find"], "Link clicks", "Eligibility starts", ["WEBSITE TRAFFIC", "LEAD"], "LEAD", ratio="9:16 story", story="Quiz: 'Aapki highest qualification?' → 'Kya padhna hai?' → swipe-up/link to Find My Course"),

# ───────────────────────── PHASE 3 (Days 31–45): University, fee & comparison ─────────────────────────
d(31, P3, O, "Carousel", "University", "How to compare", "Followers / Traffic", "MOFU", "All", "18–40", GEO_ORGANIC,
  "University compare करने का सही तरीका (7 points).",
  "Recognition for session, program availability, eligibility fit, fee breakup, max duration, exam mode, post-admission support; show /compare.",
  "Naam se nahi, fit se compare karo: 1) aapke session ke liye recognition 2) program aur specialization available 3) aapki eligibility 4) pura fee breakup 5) exam mode 6) maximum duration 7) admission ke baad support. Hamare compare tool par 4 programs side-by-side dikhte hain.",
  "Compare universities at DegreeComplete.in/compare.", "COMPARE", "trust",
  "Side-by-side comparison table mock on a laptop, Indian student pointing; navy-gold UI style.",
  "—", LP["cmp"], "Link clicks", "Saves", ["WEBSITE TRAFFIC", "FOLLOWERS"], "FOLLOWER"),
d(32, P3, O, "Static", "MBA", "Fee education", "Traffic", "MOFU", "Graduates", "21–34", GEO_ORGANIC,
  "Online MBA की total fees ₹62,000 से ₹3 लाख तक — फर्क क्यों?",
  "Fee-range explainer using source data: govt/state universities lower, private brands higher; what changes (brand, LMS, placements support, specializations). Verify current before posting.",
  "Partner universities mein Online MBA ki total fee lagbhag ₹62,000 se ₹3 lakh tak range karti hai (SOURCE, July-2026; current verify karo). Fark brand, LMS, specializations aur support ka hota hai — degree sab jagah university ki hoti hai. Sahi sawaal: aapke goal ke liye kaunsi value deti hai?",
  "See MBA fees by university.", "MBAFEES", "mba",
  "Fee slider graphic (abstract) beside an Indian professional; white background, navy and gold bars.",
  "—", LP["mba"], "Link clicks", "DMs", ["WEBSITE TRAFFIC", "WHATSAPP"], "LEAD"),
d(33, P3, O, "Reel", "General", "What's in the fee", "Followers", "TOFU", "All", "18–40", GEO_ORGANIC,
  "Fees में क्या-क्या included है? (और क्या नहीं)",
  "Reel: registration/application (one-time), tuition (per sem/year/full), exam fee (per sem/year/subject), alumni fee at some, project fee at some — from source patterns.",
  "Fee ke 4–5 parts hote hain: registration/application (one-time), tuition (semester/annual/full plan), exam fee (per semester ya per year), aur kuch universities mein alumni ya project fee (SOURCE). Hamare page par yeh sab alag-alag dikhta hai taaki surprise na ho.",
  "Save this before you pay anywhere.", "FEES", "trust",
  "Vertical: animated stack of fee cards (abstract) sliding in over a navy background; gold labels.",
  "—", LP["uni"], "Saves", "Reach", ["FOLLOWERS", "REACH"], "FOLLOWER", ratio="9:16 vertical Reel"),
d(34, P3, O, "Carousel", "University", "University options · MBA", "Traffic", "MOFU", "Graduates", "21–34", GEO_ORGANIC,
  "Online MBA के लिए 6 तरह की university options.",
  "Group partners by type without ranking: deemed brand (NMIMS, Amity, MUJ), private multi-specialization (LPU, Chandigarh, UPES), value (VGU, Galgotias, Parul), Maharashtra-based (DPU Pune, DPU Navi Mumbai, NMIMS), state/govt (KUK, Andhra), distance option (Mangalayatan). All from SOURCE partner list.",
  "Har student ke liye same university best nahi hoti. Options: established brands (NMIMS, Amity, Manipal Jaipur), wide-specialization private universities (LPU, Chandigarh, UPES), value options (VGU, Galgotias, Parul), Maharashtra ke apne (D.Y. Patil Pune / Navi Mumbai, NMIMS), state universities (Kurukshetra, Andhra) aur distance option (Mangalayatan). Fit pehle, naam baad mein.",
  "Compare MBA universities.", "MBA", "mba",
  "Six neutral navy tiles with abstract campus icons (no real logos), Indian graduate in the centre; gold accents.",
  "—", LP["mba"], "Link clicks", "Saves", ["WEBSITE TRAFFIC"], "LEAD"),
d(35, P3, O, "Static", "General", "Recognition check", "Trust", "MOFU", "All", "18–40", GEO_ORGANIC,
  "Fake university से कैसे बचें? 4 red flags.",
  "No program-level recognition shown, fee not in writing, 'degree in 6 months' promises, pressure to pay today.",
  "Red flags: 1) program-level recognition dikhane se bachna 2) fee likhit mein na dena 3) '6 mahine mein degree' jaise promises 4) aaj hi pay karne ka pressure. Sahi platform aapko verify karne ka time deta hai — hum bhi.",
  "Share this with someone who is about to pay.", "VERIFY", "trust",
  "Warning-style navy card with four gold flags icon row; concerned then relieved Indian student.",
  "—", LP["elig"], "Shares", "Saves", ["REACH", "ENGAGEMENT"], "TRUST"),
d(36, P3, O, "Carousel", "General", "Documents", "Traffic", "MOFU", "All", "18–40", GEO_ORGANIC,
  "Admission के लिए कौन से documents चाहिए? (Checklist)",
  "From the 20-item source checklist: mandatory (10th, 12th, Aadhaar, photo, signature), PG extra (graduation marksheets, degree/provisional), conditional (category, work-ex, name change).",
  "Sab ke liye: 10th aur 12th marksheet + certificate, Aadhaar, photo, signature. PG ke liye: graduation ki saari marksheets aur degree/provisional certificate. Conditional: category certificate, work-experience letters, name-change proof (SOURCE). Soft copies, verify pehle, admission baad mein.",
  "Full checklist: DegreeComplete.in/documents-required.", "DOCS", "trust",
  "Neat stack of document folders with gold tabs, a phone scanning a page; white desk, navy header.",
  "—", LP["docs"], "Link clicks", "Saves", ["WEBSITE TRAFFIC", "FOLLOWERS"], "FOLLOWER"),
d(37, P3, O, "Reel", "BBA", "Fee comparison · BBA", "Traffic", "MOFU", "12th pass + parents", "18–24", GEO_ORGANIC,
  "Online BBA fees: ₹64,000 से ₹1.5 लाख — क्या फर्क है?",
  "Reel with source ranges: distance option lowest (Mangalayatan ~₹64k), state/value (KUK ~₹73k, VGU, Parul), private brands (MUJ, Amity, NMIMS ~₹1.3–1.5L). Verify before posting.",
  "BBA ki total fee partner universities mein lagbhag ₹64,000 se ₹1.5 lakh tak hai (SOURCE, verify current). Distance aur state options kam, private brands zyada. Fees aap university ko pay karte ho, aur EMI/loan options kuch universities mein available hain.",
  "See BBA fees by university.", "BBA", "bba",
  "Vertical: parent and student at a dining table looking at a tablet, warm evening light; navy bottom band with gold rupee motif.",
  "—", LP["bba"], "Link clicks", "DMs", ["WEBSITE TRAFFIC", "WHATSAPP"], "LEAD", ratio="9:16 vertical Reel"),
d(38, P3, O, "Static", "General", "EMI / loan", "Engagement", "MOFU", "All", "18–40", GEO_ORGANIC,
  "Fees एक साथ नहीं दे सकते? EMI options समझो.",
  "Explain semester/annual/full plans and no-cost EMI via lender partners at several universities (SOURCE); terms by lender; we never collect fees.",
  "Zyadatar universities semester, annual ya full-payment plan deti hain; kai universities lender partners ke saath no-cost EMI bhi offer karti hain (SOURCE). Terms lender/university tay karte hain. Hum sirf batate hain kaunsa plan aapke liye available hai — fees seedha university ko jaati hai.",
  "Message EMI with your course.", "EMI", "trust",
  "Calendar with gold-marked instalment dates and a laptop; Indian professional's hands; white and navy.",
  "—", LP["find"], "DMs", "Saves", ["WHATSAPP", "ENGAGEMENT"], "LEAD"),
d(39, P3, O, "Carousel", "BCA", "University options · BCA", "Traffic", "MOFU", "12th pass", "18–24", GEO_ORGANIC,
  "Online BCA specializations by university.",
  "Map from source catalogue: AI/Data Science (MUJ, Amrita, Chandigarh, Shoolini), Cloud/Cyber (MUJ, UPES, Chandigarh, Shoolini), Fintech (Amity), General (LPU, Parul, Galgotias, UU, VGU). Verify list before posting.",
  "AI & Data Science, Cloud, Cyber Security, Full-Stack, Fintech — alag universities alag specializations deti hain (SOURCE catalogue). Pehle decide karo kis field mein jaana hai, phir university. Hum aapke 12th subjects ke hisaab se eligible options filter karte hain.",
  "Explore BCA by specialization.", "BCA", "bca",
  "Grid of five specialization icons (abstract) over a young Indian coder; navy-gold layout.",
  "—", LP["bca"], "Link clicks", "Saves", ["WEBSITE TRAFFIC"], "LEAD"),
d(40, P3, O, "Reel", "General", "Counsellor expertise", "Trust", "MOFU", "All", "18–40", GEO_ORGANIC,
  "Counsellor से पहली call में क्या पूछें? (5 सवाल)",
  "Reel of the questions a good counsellor answers: recognition, eligibility for me, full fee, max duration, who supports after admission.",
  "Pehli call mein poochho: 1) mere session ke liye recognition 2) kya main eligible hoon (marks/subject) 3) pura fee breakup 4) maximum duration 5) admission ke baad support kaun karega. Jo counsellor in paanch ka seedha jawab de, wahi bharose layak hai.",
  "Test us — message CALL.", "CALL", "trust",
  "Vertical: friendly Indian counsellor with a headset, white desk, five gold question chips floating.",
  "—", LP["process"], "DMs", "Reach", ["WHATSAPP", "CALL"], "TRUST", ratio="9:16 vertical Reel"),
d(41, P3, O, "Carousel", "MCA", "University options · MCA", "Traffic", "MOFU", "Graduates", "21–30", GEO_ORGANIC,
  "Online MCA: AI/ML, Data Science, Cyber — कहाँ क्या मिलता है?",
  "Source catalogue mapping: AI&ML (MUJ, UPES, Chandigarh, Shoolini, DPU Pune, Amrita), Data Science (LPU, Sharda*, Shoolini, UPES), Cyber (Amity, Amrita, MUJ, UPES, LPU), Full-stack (LPU, Chandigarh, Parul). *on hold — exclude.",
  "MCA mein AI & ML, Data Science, Cyber Security & Forensics, Cloud, Full-Stack jaise specializations partner universities mein hain (SOURCE). Fees lagbhag ₹76,000 se ₹2.3 lakh tak (SOURCE, verify). Maths eligibility clear hai toh options kaafi hain.",
  "Compare MCA programs.", "MCA", "mca",
  "Indian graduate at a workstation with abstract neural-network visual; navy-gold framing.",
  "—", LP["mca"], "Link clicks", "Saves", ["WEBSITE TRAFFIC"], "LEAD"),
d(42, P3, O, "Static", "General", "Maharashtra", "Traffic", "MOFU", "Maharashtra", "18–40", "Maharashtra (Mumbai, Thane, Navi Mumbai, Pune, Nagpur, Nashik, Sambhajinagar)",
  "Mumbai/Pune में हो? ये universities आपके पास हैं.",
  "Highlight Maharashtra-based partners (NMIMS Mumbai, D.Y. Patil Navi Mumbai, D.Y. Patil Pune) + national online options; note ODL jurisdiction check.",
  "Maharashtra ke students ke liye NMIMS (Mumbai), D.Y. Patil Navi Mumbai aur D.Y. Patil Pune jaise partner universities local hain, aur online mode mein desh bhar ki universities open hain. Distance (ODL) programs mein territorial rules ho sakte hain — hum pehle check karte hain.",
  "Explore universities.", "MUMBAI", "trust",
  "Mumbai skyline at golden hour softly blurred behind a young Indian professional with a laptop; navy-gold overlay.",
  "—", LP["uni"], "Link clicks", "Profile visits", ["WEBSITE TRAFFIC", "REACH"], "LEAD"),
d(43, P3, O, "Reel", "General", "Application process", "Trust", "MOFU", "All", "18–40", GEO_ORGANIC,
  "Enquiry से admission तक — 8 steps, कितना time?",
  "Reel walking the source admission steps with timelines: counselling same day → documents 1 day → portal registration → fee → verification 2–7 working days → LMS 1–2 weeks.",
  "Counselling aur course selection (same day) → documents collect aur pre-check (1 din) → university portal par registration → fee (ya EMI) → university verification (2–7 working days) → provisional admission, LMS access, ABC/APAAR ID (1–2 hafte) (SOURCE). Simple hai jab koi saath ho.",
  "Save this. Start with an eligibility check.", "PROCESS", "trust",
  "Vertical: eight-step vertical timeline with gold nodes on navy, Indian student's phone at the end showing an admission screen (abstract).",
  "—", LP["process"], "Saves", "Link clicks", ["FOLLOWERS", "WEBSITE TRAFFIC"], "TRUST", ratio="9:16 vertical Reel"),
d(44, P3, O, "Carousel", "BA / B.Com", "Fee comparison · Graduation", "Traffic", "MOFU", "Academic gap", "21–34", GEO_ORGANIC,
  "Graduation complete करने की fees — ₹34,000 से शुरू.",
  "Source ranges: Mangalayatan distance BA ~₹34k, KUK BA/B.Com ~₹73k, Parul ₹70k, private brands ~₹1–1.6L. Verify before posting.",
  "Online/Distance BA aur B.Com ki total fees lagbhag ₹34,000 se ₹1.6 lakh tak range karti hai (SOURCE, verify current). Sabse kam distance aur state options mein. EMI kuch universities mein available hai. Budget batao — hum uske andar options dikhayenge.",
  "See BA & B.Com fees.", "GRADUATION", "grad",
  "Indian woman, 26, in a shop-owner setting with a laptop at the counter, warm light; navy-gold card.",
  "—", LP["grad"], "Link clicks", "DMs", ["WEBSITE TRAFFIC", "WHATSAPP"], "LEAD"),
d(45, P3, O, "Story set + Static", "University", "Interactive", "Engagement", "MOFU", "All", "18–40", GEO_ORGANIC,
  "Poll: आप university कैसे choose करते हो?",
  "Polls (brand vs fee vs nearest vs specialization) + follow-up static summarising results and pointing to /compare.",
  "Brand, fee, nearest campus ya specialization — aap kis basis par choose karte ho? Poll ke results aaj shaam post karenge. Sahi jawab: apni eligibility aur goal ke basis par compare karo.",
  "Vote on the story. Compare at DegreeComplete.in/compare.", "COMPARE", "gen",
  "Vertical story: four poll options on navy with gold bars; small Indian student illustration.",
  "—", LP["cmp"], "Replies", "Link clicks", ["ENGAGEMENT", "WEBSITE TRAFFIC"], "FOLLOWER", ratio="9:16 story", story="4-option poll + 'Ask me anything about fees' question box"),

# ───────────────────────── PHASE 4 (Days 46–60): Problem-solving + lead magnets ─────────────────────────
d(46, P4, O, "Reel", "General", "Lead magnet · Course Finder", "Lead", "MOFU", "All", "18–40", GEO_ORGANIC,
  "Confused? 5 सवालों में course decide — free.",
  "Lead magnet 1: Free Course Finder demo reel → /find-course; lead gate inside.",
  "Kya padhein, kahan se, kitne mein — sab ek saath sochna mushkil hai. Free Course Finder mein 5 sawaal ke baad sirf eligible programs dikhte hain, phir advisor exact eligibility aur fee confirm karta hai. Koi charge nahi, koi obligation nahi.",
  "Find My Course — link in bio.", "COURSE", "gen",
  "Vertical: phone screen recording of the finder; navy background; gold 'Free' badge (not a fake seal).",
  "—", LP["find"], "Eligibility starts", "Leads", ["LEAD", "WEBSITE TRAFFIC"], "LEAD", ratio="9:16 vertical Reel"),
d(47, P4, O, "Static", "MBA", "Lead magnet · MBA comparison", "Lead", "MOFU", "Graduates", "21–34", GEO_ORGANIC,
  "Free: Online MBA University Comparison (2026).",
  "Lead magnet 3: comparison sheet (eligibility, duration, fee range, specializations, EMI) for A-tier MBA partners; delivered on WhatsApp after form.",
  "Ek hi sheet mein partner universities ke Online MBA: eligibility, duration, fee breakup, specializations aur EMI availability — sab source se, koi guess nahi. WhatsApp par free milegi.",
  "Message MBA to get the comparison.", "MBA", "mba",
  "Tablet showing a clean comparison grid (abstract), gold pen, Indian professional's hand; white desk, navy header.",
  "—", LP["mba"], "WhatsApp conversations", "Leads", ["WHATSAPP", "LEAD"], "LEAD"),
d(48, P4, O, "Carousel", "BA / B.Com", "Lead magnet · Graduation guidance", "Lead", "MOFU", "Academic gap", "21–34", GEO_ORGANIC,
  "Graduation Completion Guide: gap के बाद कैसे शुरू करें.",
  "Lead magnet 4: 6 slides — who is eligible after a gap, documents, which universities accept pass marks, duration, EMI, first step.",
  "Gap 2 saal ka ho ya 10 saal ka — 12th pass ho toh Online BA/B.Com ke raste khule hain (SOURCE eligibility). Kuch universities gap-year undertaking maangti hain (SOURCE). Guide mein documents, fees aur first step sab hai.",
  "Message GRADUATION for the guide.", "GRADUATION", "grad",
  "Indian man, 32, holding an old marksheet folder and a new laptop; hopeful; navy-gold layout.",
  "—", LP["grad"], "WhatsApp conversations", "Leads", ["WHATSAPP", "LEAD"], "LEAD"),
d(49, P4, O, "Reel", "General", "Lead magnet · Eligibility check", "Lead", "MOFU", "All", "18–40", GEO_ORGANIC,
  "'Main eligible hoon ya nahi?' — 2 minute में जवाब.",
  "Lead magnet 2: eligibility check explainer; what we check (marks, subjects, gap, work-ex); free.",
  "Marks, 12th subjects, graduation stream, gap aur work experience — inhi se eligibility decide hoti hai. Hum 2 minute mein bata dete hain kaunse programs aapke liye open hain aur kaunse nahi. Free, bina pressure.",
  "Check My Eligibility — link in bio.", "ELIGIBLE", "trust",
  "Vertical: green tick appearing on a phone screen held by an Indian student; navy background.",
  "—", LP["elig"], "Leads", "Eligibility starts", ["LEAD"], "LEAD", ratio="9:16 vertical Reel"),
d(50, P4, O, "Carousel", "BCA", "Lead magnet · BCA vs BBA guide", "Lead", "MOFU", "12th pass", "18–24", GEO_ORGANIC,
  "BCA vs BBA Guide — 12th के बाद सही चुनाव.",
  "Lead magnet 8: eligibility, subjects, specializations, careers, next degree, fee ranges (SOURCE).",
  "Dono 3 saal, dono ghar se, dono ke baad PG. Fark: BCA ke liye Maths preferred (kuch mein mandatory), tech careers; BBA any stream, business careers (SOURCE). Guide mein fees aur universities bhi.",
  "Message BCA or BBA for the guide.", "BCA", "bca",
  "Two-column guide cover mock on a navy background; young Indian student silhouette; gold divider.",
  "—", LP["bca"], "WhatsApp conversations", "Leads", ["WHATSAPP", "LEAD"], "LEAD"),
d(51, P4, O, "Static", "General", "Lead magnet · Online vs Distance", "Lead", "MOFU", "All", "18–40", GEO_ORGANIC,
  "Free guide: Online vs Distance — आपके लिए क्या सही है?",
  "Lead magnet 5: PDF/WhatsApp guide with a 6-question decision flow.",
  "Location, schedule, exam preference, budget, course aur university rules — in 6 sawaalon se mode decide hota hai. Guide free hai; padh kar bhi confusion rahe toh advisor se baat karo.",
  "Message MODE for the guide.", "MODE", "gen",
  "Split navy/gold card with two abstract mode icons; Indian student between.",
  "—", LP["find"], "WhatsApp conversations", "Saves", ["WHATSAPP", "LEAD"], "LEAD"),
d(52, P4, O, "Reel", "MBA", "MBA · Working professional", "Lead", "MOFU", "Working", "24–36", GEO_ORGANIC,
  "MBA करना है पर resign नहीं कर सकते? यही solution है.",
  "Reel: one working professional's week + program structure; CTA to eligibility.",
  "Online MBA mein classes recorded/weekend, exams online, aur most universities mein entrance exam nahi (SOURCE). Resign nahi, transfer nahi, leave nahi. 2 saal baad MBA on your CV.",
  "Check eligibility — message MBA.", "MBA", "mba",
  "Vertical: professional on a rooftop office terrace at evening with a laptop; navy skyline; gold text area.",
  "—", LP["mba"], "Leads", "DMs", ["LEAD", "WHATSAPP"], "LEAD", ratio="9:16 vertical Reel"),
d(53, P4, O, "Carousel", "General", "Lead magnet · University checklist", "Lead", "MOFU", "All", "18–40", GEO_ORGANIC,
  "University Selection Checklist (10 points) — free.",
  "Lead magnet 10: recognition, eligibility, fee breakup, EMI, exam mode, max duration, specialization list, LMS, support, refund policy.",
  "Enrol karne se pehle 10 cheezein tick karo — recognition se refund policy tak. Checklist free hai, aur hum har point aapke shortlist ke liye bhar kar de sakte hain.",
  "Message CHECKLIST.", "CHECKLIST", "trust",
  "Clipboard with a 10-point list and gold ticks, Indian student's hands; white and navy.",
  "—", LP["cmp"], "WhatsApp conversations", "Saves", ["WHATSAPP", "LEAD"], "LEAD"),
d(54, P4, O, "Static", "MCA", "MCA · Career switch", "Lead", "MOFU", "Non-IT graduates", "22–32", GEO_ORGANIC,
  "Career switch to IT — MCA eligibility 2 minute में check करो.",
  "Lead post: Maths filter + bridge course; CTA eligibility.",
  "Non-IT graduate ke liye MCA ka pehla sawaal Maths ka hai (10+2 ya graduation) — jahan allowed hai wahan bridge course (SOURCE). Aapka case kya hai, 2 minute mein batate hain.",
  "Check MCA eligibility — message MCA.", "MCA", "mca",
  "Indian professional, 27, at a laptop with a notebook of formulas; navy-gold composition.",
  "—", LP["mca"], "Leads", "DMs", ["LEAD", "WHATSAPP"], "LEAD"),
d(55, P4, O, "Reel", "General", "Student mistakes · Documents", "Followers / Lead", "MOFU", "All", "18–40", GEO_ORGANIC,
  "Documents की ये 4 galtiyan admission रोक देती हैं.",
  "Name mismatch across documents, blurry scans, missing consolidated marksheet, Aadhaar-mobile not linked (ABC ID) — all from source checklist.",
  "1) Naam documents mein alag-alag 2) blurry scan 3) graduation ki consolidated marksheet missing 4) Aadhaar se mobile link nahi (ABC/APAAR ID ke liye zaroori) (SOURCE). Hum pre-check karte hain taaki application reject na ho.",
  "Save this. Full checklist at DegreeComplete.in/documents-required.", "DOCS", "trust",
  "Vertical: four document thumbnails with red/green markers on navy; Indian student's phone scanning.",
  "—", LP["docs"], "Saves", "Link clicks", ["FOLLOWERS", "WEBSITE TRAFFIC"], "FOLLOWER", ratio="9:16 vertical Reel"),
d(56, P4, O, "Carousel", "MBA", "Lead magnet · MBA specialization guide", "Lead", "MOFU", "Graduates", "21–34", GEO_ORGANIC,
  "MBA Specialization Guide — कौन सा आपके career के लिए?",
  "Lead magnet 7: Finance, Marketing, HR, Analytics, Operations, Digital Marketing, IT — who it suits, roles, which partners offer it (SOURCE).",
  "Har specialization ke liye: kis profile ko suit karta hai, kaunse roles, aur kaunsi partner universities offer karti hain (SOURCE catalogue). Guide WhatsApp par free.",
  "Message SPECIALIZATION.", "SPECIALIZATION", "mba",
  "Seven abstract specialization tiles around a young Indian professional; navy-gold.",
  "—", LP["mba"], "WhatsApp conversations", "Leads", ["WHATSAPP", "LEAD"], "LEAD"),
d(57, P4, O, "Static", "BBA", "BBA · 12th pass", "Lead", "MOFU", "12th pass", "18–24", GEO_ORGANIC,
  "12th pass हो? Online BBA के लिए आज eligibility check करो.",
  "Direct lead post: eligibility + fee range + no entrance (SOURCE).",
  "Kisi bhi stream se 12th pass — Online BBA ke liye eligible ho sakte ho (SOURCE). Fees ₹64,000 se ₹1.5 lakh (verify current), EMI options. 2 minute ka eligibility check, phir decision aapka.",
  "Check My Eligibility — link in bio.", "BBA", "bba",
  "Young Indian woman, 19, with a tablet outside a college gate (generic), confident; navy-gold.",
  "—", LP["bba"], "Leads", "Link clicks", ["LEAD"], "LEAD"),
d(58, P4, O, "Reel", "General", "Career upgrade guide", "Lead", "MOFU", "Working", "24–40", GEO_ORGANIC,
  "Career Upgrade Guide: degree + skill = promotion.",
  "Lead magnet 9: which PG/certificate fits which career stage; PG certificates (UPES) and MBA options (SOURCE).",
  "Career ke stage ke hisaab se: entry level → graduation complete; 2–5 saal → MBA/MCA; 5+ saal → Executive/PG certificate (SOURCE options). Guide free — apna stage batao.",
  "Message UPGRADE.", "UPGRADE", "gen",
  "Vertical: staircase graphic with gold steps, Indian professional climbing; navy.",
  "—", LP["find"], "WhatsApp conversations", "Leads", ["WHATSAPP", "LEAD"], "LEAD", ratio="9:16 vertical Reel"),
d(59, P4, O, "Carousel", "General", "Lead magnet · Course & fee comparison", "Lead", "MOFU", "All", "18–40", GEO_ORGANIC,
  "Course & Fee Comparison — 4 programs side by side, free.",
  "Lead magnet 6: demo of /compare with real fields (registration, exam, semester, annual, total, EMI, eligibility, documents).",
  "4 programs side-by-side: eligibility, duration, registration/exam/semester/annual/total fee, EMI, documents — sab ek screen par. Compare karo, phir advisor se confirm karo.",
  "Compare now — link in bio.", "COMPARE", "trust",
  "Laptop screen with a four-column comparison grid (abstract), Indian student comparing; navy-gold.",
  "—", LP["cmp"], "Link clicks", "Compare completed", ["WEBSITE TRAFFIC", "LEAD"], "LEAD"),
d(60, P4, O, "Story set + Static", "General", "Talk to an expert", "Lead / Call", "BOFU", "All", "18–40", GEO_ORGANIC,
  "Aaj ek call — aur clarity mil jaayegi.",
  "Story CTA day: 'Call an Education Expert' + WhatsApp; static summarising the four free tools.",
  "Course Finder, Eligibility Check, University Comparison, Documents Checklist — chaar free tools. Aur ek advisor jo sach batata hai. Call ya WhatsApp: 98 33 07 44 76.",
  "Call an Education Expert: 98 33 07 44 76.", "CALL", "trust",
  "Vertical story: phone with call and WhatsApp buttons on navy, gold headline.",
  "—", LP["home"], "Calls", "WhatsApp conversations", ["CALL", "WHATSAPP"], "CONVERSION", ratio="9:16 story", story="Countdown-free CTA stories: Call / WhatsApp / Check eligibility link stickers"),

# ───────────────────────── PHASE 5 (Days 61–75): Performance scale (15 paid) ─────────────────────────
d(61, P5, PA, "Video Ad (Reel)", "MBA", "Awareness · Career growth", "Awareness / Video views", "TOFU", "Graduates + working", "22–34", GEO_SCALE,
  "आपका अगला promotion एक degree दूर हो सकता है.",
  "PA-05 Awareness 1/6. 15-sec cinematic: professional's day, subtle text; no hard sell; ThruPlay optimised.",
  "Skill hai, experience hai — qualification ki line CV mein khaali hai? Online MBA se woh line bhar sakti hai, job chhode bina. Pehle dekho kaunse programs aapke liye open hain.",
  "Explore Online MBA.", "MBA", "mba",
  "Vertical cinematic: Indian professional walking through a modern office lobby at morning, confident; navy grade, gold text.",
  "Video views (ThruPlay)", LP["mba"], "ThruPlay rate", "Cost per ThruPlay", ["REACH", "RETARGETING"], "CONVERSION", ratio="9:16 vertical Reel"),
d(62, P5, PA, "Lead Ad (Static)", "MBA", "MBA · Qualification upgrade", "Lead", "MOFU", "Graduates in jobs", "24–34", GEO_SCALE,
  "Graduate हो, job है — अब MBA. बिना entrance exam.",
  "PA-06 Lead 5/10. Static with 3 facts + instant form (qualification, work-ex, city).",
  "Most partner universities mein Online MBA ke liye entrance exam nahi hai — bachelor's degree aur minimum marks kaafi hain (SOURCE). 2 saal, online exams, EMI options. Eligibility check free.",
  "Check My Eligibility", "MBA", "mba",
  "Indian professional woman, 29, at a standing desk, city view; navy overlay with gold line.",
  "Leads (instant form)", LP["mba"], "Cost per qualified lead", "Lead form conversion", ["LEAD"], "LEAD"),
d(63, P5, PA, "Video Ad (Reel)", "BA / B.Com", "Awareness · Graduation", "Awareness / Video views", "TOFU", "Academic gap", "21–34", GEO_SCALE,
  "Graduation अधूरी रह गई थी — अब नहीं.",
  "PA-07 Awareness 2/6. 12-sec emotional but composed: an old marksheet, a new login; text-light.",
  "Zindagi ne graduation pause kar di thi. Online BA/B.Com se woh pause ab khatam ho sakta hai — ghar se, job ke saath, 12th pass eligibility (SOURCE).",
  "See how it works.", "GRADUATION", "grad",
  "Vertical: hands opening an old marksheet folder, cut to a laptop login screen (abstract), warm-to-navy grade.",
  "Video views (ThruPlay)", LP["grad"], "ThruPlay rate", "Cost per ThruPlay", ["REACH", "RETARGETING"], "CONVERSION", ratio="9:16 vertical Reel"),
d(64, P5, PA, "Lead Ad (Reel)", "BBA", "BBA · Flexible degree", "Lead", "MOFU", "12th pass", "18–24", GEO_SCALE,
  "College नहीं जा सकते? BBA फिर भी हो सकता है.",
  "PA-08 Lead 6/10. Vertical: student at work/home, phone with program list; instant form.",
  "Family business, job ya doori ki wajah se college nahi ja paate? Online BBA mein classes online, exams online, 3 saal (SOURCE). Eligibility 12th pass. Free check.",
  "Check My Eligibility", "BBA", "bba",
  "Vertical: young Indian man at a family shop counter with a laptop; warm light; navy text area.",
  "Leads (instant form)", LP["bba"], "Cost per qualified lead", "CTR", ["LEAD"], "LEAD", ratio="9:16 vertical Reel"),
d(65, P5, PA, "Engagement Ad (Carousel)", "General", "Engagement · Online vs Distance", "Engagement", "TOFU", "All", "18–40", GEO_SCALE,
  "Online या Distance? 30 seconds में decide.",
  "PA-09 Engagement 1/4. Boost of the Day-3 carousel logic with a comment CTA; builds engager audience.",
  "Mode ka decision location, schedule aur course par hota hai. Comment mein apna city aur course likho — hum batayenge Online ya Distance aapke liye kaunsa fit hai.",
  "Comment your city + course.", "MODE", "gen",
  "Split navy/gold carousel cover with two Indian students; clean typography zone.",
  "Engagement (post)", LP["find"], "Comments", "Saves", ["ENGAGEMENT", "RETARGETING"], "FOLLOWER"),
d(66, P5, PA, "Lead Ad (Static)", "BCA", "BCA · IT career", "Lead", "MOFU", "12th pass, tech", "18–24", GEO_SCALE,
  "12th के बाद IT career — Online BCA (AI / Data / Cyber).",
  "PA-10 Lead 7/10. Static, specialization chips, instant form.",
  "AI & Data Science, Cyber Security, Cloud — Online BCA specializations partner universities mein (SOURCE). 3 saal, ghar se. Kuch universities 12th mein Maths maangti hain — pehle eligibility check.",
  "Check My Eligibility", "BCA", "bca",
  "Indian teenager with a laptop, abstract circuit motif, navy setup with gold accent.",
  "Leads (instant form)", LP["bca"], "Cost per qualified lead", "CTR", ["LEAD"], "LEAD"),
d(67, P5, PA, "Traffic Ad (Static)", "MBA", "Traffic · MBA comparison", "Traffic", "MOFU", "Graduates", "22–34", GEO_SCALE,
  "Online MBA: 20+ universities, एक page पर compare.",
  "PA-11 Traffic 1/4. Drive to /online-mba with fee-from figure (verify current).",
  "Eligibility, duration, fee breakup aur specializations — partner universities ke Online MBA programs ek page par. Lowest fee first, koi hidden charge nahi.",
  "Compare Universities", "MBA", "mba",
  "Laptop with a program grid (abstract) on a white desk; Indian professional's hands; navy header.",
  "Traffic (landing page views)", LP["mba"], "Landing page views", "CPC", ["WEBSITE TRAFFIC", "RETARGETING"], "LEAD"),
d(68, P5, PA, "Video Ad (Reel)", "MCA", "Awareness · Tech upgrade", "Awareness / Video views", "TOFU", "Graduates", "21–30", GEO_SCALE,
  "Graduate से AI/Data professional — Online MCA.",
  "PA-12 Awareness 3/6. 12-sec: graduate's laptop transforms (abstract), specializations flash.",
  "Online MCA mein AI & ML, Data Science, Cyber Security jaise specializations (SOURCE). 2 saal, job ke saath. Maths eligibility clear hai toh raasta open hai.",
  "Explore Online MCA.", "MCA", "mca",
  "Vertical: Indian graduate at a desk, abstract data streams over navy; gold accents.",
  "Video views (ThruPlay)", LP["mca"], "ThruPlay rate", "Cost per ThruPlay", ["REACH", "RETARGETING"], "CONVERSION", ratio="9:16 vertical Reel"),
d(69, P5, PA, "Lead Ad (Reel)", "BA / B.Com", "Graduation · Working professional", "Lead", "MOFU", "Working, no degree", "22–36", GEO_SCALE,
  "Job में हो, degree नहीं है? Online B.Com/BA — 12th pass से.",
  "PA-13 Lead 8/10. Vertical testimonial-free; facts + instant form.",
  "12th ke baad seedha kaam shuru kar diya tha? Ab Online BA/B.Com se graduation complete karo — most universities mein bina entrance exam, 3 saal, ghar se (SOURCE). Eligibility check free.",
  "Check My Eligibility", "GRADUATION", "grad",
  "Vertical: Indian delivery-rider/office assistant persona in uniform, phone in hand at a break, hopeful; navy text band.",
  "Leads (instant form)", LP["grad"], "Cost per qualified lead", "Qualified lead rate", ["LEAD"], "LEAD", ratio="9:16 vertical Reel"),
d(70, P5, PA, "Engagement Ad (Reel)", "General", "Engagement · Mistakes", "Engagement", "TOFU", "All", "18–34", GEO_SCALE,
  "University choose करने से पहले ये mistake मत करना.",
  "PA-14 Engagement 2/4. Boost of a mistakes reel; save/share CTA.",
  "Ad dekh kar university mat chuno. Recognition (apne session ke liye), eligibility, likhit fee aur support — chaar cheezein pehle. Save karo, kisi ko bhejo jo enrol karne wala hai.",
  "Save and share.", "VERIFY", "trust",
  "Vertical: Indian student stopping a 'pay now' button (abstract) with a hand; navy-gold.",
  "Engagement (video)", LP["elig"], "Saves + shares", "ThruPlay", ["ENGAGEMENT", "RETARGETING"], "FOLLOWER", ratio="9:16 vertical Reel"),
d(71, P5, PA, "Traffic Ad (Carousel)", "BBA / BCA", "Traffic · After 12th", "Traffic", "MOFU", "12th pass", "18–24", GEO_SCALE,
  "12th के बाद online degree — सारे options एक जगह.",
  "PA-15 Traffic 2/4. Drive to /online-degree-after-12th; cards for BBA, BCA, BA, B.Com.",
  "BBA, BCA, BA, B.Com — 12th ke baad ke saare online options, eligibility aur fees ke saath ek page par. Apne 12th subjects ke hisaab se filter karo.",
  "View Programs", "12TH", "bba",
  "Four program tiles with abstract icons, young Indian student centre; navy-gold.",
  "Traffic (landing page views)", LP["grad"], "Landing page views", "CPC", ["WEBSITE TRAFFIC", "RETARGETING"], "LEAD"),
d(72, P5, PA, "Video Ad (Reel)", "BBA", "Awareness · Career foundation", "Awareness / Video views", "TOFU", "12th pass + parents", "18–24", GEO_SCALE,
  "Business की foundation — BBA, घर से.",
  "PA-16 Awareness 4/6. 12-sec: student + parent, business setting, subtle.",
  "Family business sambhalna ho ya corporate career shuru karni ho — Online BBA se management ki foundation ghar se banti hai. 3 saal, 12th pass eligibility (SOURCE).",
  "Explore Online BBA.", "BBA", "bba",
  "Vertical: father and daughter at a small business counter, tablet in hand; warm light; navy text area.",
  "Video views (ThruPlay)", LP["bba"], "ThruPlay rate", "Cost per ThruPlay", ["REACH", "RETARGETING"], "CONVERSION", ratio="9:16 vertical Reel"),
d(73, P5, PA, "Lead Ad (Static)", "MBA", "MBA · Affordable / flexible", "Lead", "MOFU", "Graduates, budget-conscious", "22–34", GEO_SCALE,
  "Online MBA ₹62,000 से — EMI के साथ. (University के हिसाब से)",
  "PA-17 Lead 9/10. Fee-from creative (verify current) + EMI mention; instant form with budget field.",
  "Partner universities mein Online MBA ki total fee ₹62,000 se shuru hoti hai (SOURCE, verify current) aur kai mein EMI options hain. Budget batao — hum uske andar eligible programs dikhayenge.",
  "Get Fee Details", "MBAFEES", "mba",
  "Indian professional at a home desk with a calculator and laptop; white and navy, gold rupee accent.",
  "Leads (instant form)", LP["mba"], "Cost per qualified lead", "Budget-qualified rate", ["LEAD"], "LEAD"),
d(74, P5, PA, "Traffic Ad (Reel)", "General", "Traffic · Course Finder", "Traffic", "MOFU", "All", "18–40", GEO_SCALE,
  "5 सवाल → आपके eligible programs.",
  "PA-18 Traffic 3/4. Screen-record reel of /find-course.",
  "Qualification, course, mode, budget, goal — 5 sawaal ke baad sirf wahi programs jinke liye aap eligible ho. Free, 2 minute.",
  "Find My Course", "COURSE", "gen",
  "Vertical: phone screen recording of the finder on navy; gold progress dots.",
  "Traffic (landing page views)", LP["find"], "Landing page views", "Eligibility starts", ["WEBSITE TRAFFIC", "LEAD"], "LEAD", ratio="9:16 vertical Reel"),
d(75, P5, PA, "Lead Ad (Reel)", "MBA", "MBA · Specialization", "Lead", "MOFU", "Graduates", "22–34", GEO_SCALE,
  "Finance, Marketing, HR, Analytics — आपका MBA specialization?",
  "PA-19 Lead 10/10. Vertical with specialization chips; instant form asks target specialization.",
  "Partner universities mein Finance, Marketing, HR, Business Analytics, Operations, Digital Marketing, IT jaise MBA specializations (SOURCE). Apna target role batao — hum matching programs aur fees bhejenge.",
  "Get Course Details", "SPECIALIZATION", "mba",
  "Vertical: Indian professional choosing a card from a fan of seven (abstract labels), navy-gold.",
  "Leads (instant form)", LP["mba"], "Cost per qualified lead", "CTR", ["LEAD"], "LEAD", ratio="9:16 vertical Reel"),

# ───────────────────────── PHASE 6 (Days 76–90): Retargeting + conversion ─────────────────────────
d(76, P6, PA, "Retargeting Ad (Static)", "General", "Retargeting · Still deciding", "Retargeting / Lead", "BOFU", "Engagers + video viewers (30d)", "18–40", GEO_RT,
  "अभी भी confused? चलिए साथ में decide करते हैं.",
  "PA-20 Retargeting 1/3. Soft message to Instagram engagers and video viewers; CTA to Course Finder.",
  "Aapne humare posts dekhe — matlab decision chal raha hai. Bina pressure ke: 5 sawaal, eligible programs, aur ek advisor jo sach batata hai. Jab ready ho, tab.",
  "Find My Course", "COURSE", "gen",
  "Calm Indian student on a balcony with a notebook, thinking; navy-gold minimal.",
  "Leads / Traffic (retargeting: engagers 30d)", LP["find"], "Cost per lead (retarget)", "Frequency", ["RETARGETING", "LEAD"], "CONVERSION"),
d(77, P6, PA, "Retargeting Ad (Reel)", "MBA", "Retargeting · Course-page visitors", "Retargeting / Lead", "BOFU", "Website + MBA page visitors (30d)", "22–34", GEO_RT,
  "आपने MBA programs देखे — eligibility check किया?",
  "PA-21 Retargeting 2/3. Pixel audience: viewed /online-mba or program pages, no lead.",
  "Programs dekh liye, fees dekh li — ab sirf ek step: eligibility. 2 minute, free, aur aapko pata chal jaayega kaunse programs actually open hain.",
  "Check My Eligibility", "MBA", "mba",
  "Vertical: phone showing a program page (abstract) with a gold 'eligible' tick; navy background.",
  "Leads (retargeting: website visitors 30d, exclude leads)", LP["mba"], "Cost per lead (retarget)", "Conversion rate", ["RETARGETING", "LEAD"], "CONVERSION", ratio="9:16 vertical Reel"),
d(78, P6, PA, "Conversion Ad (Static)", "General", "Conversion · Leads not applied", "Conversion", "BOFU", "Leads without application (CRM)", "18–40", GEO_RT,
  "Aapki eligibility clear hai — अब application सिर्फ 10 minute.",
  "PA-22 Conversion 1/3. Custom audience from CRM (lead submitted, no application). CTA Apply Now.",
  "Eligibility confirm ho chuki hai. Application form 10 minute ka hai, documents baad mein dashboard se upload kar sakte ho, aur fees seedha university ko. Aapka counsellor saath hai.",
  "Start Your Application", "APPLY", "trust",
  "Indian student pressing 'Apply' on a laptop (abstract), relaxed smile; white desk, navy header.",
  "Conversions (custom audience: leads without application)", "/apply", "Application starts", "Cost per application", ["APPLICATION", "RETARGETING"], "CONVERSION"),
d(79, P6, PA, "Engagement Ad (Story)", "General", "Engagement · FAQ", "Engagement", "MOFU", "Engagers + visitors", "18–40", GEO_RT,
  "आपके top 5 सवाल — जवाब यहाँ.",
  "PA-23 Engagement 3/4. Story-format ad answering FAQs (recognition, fees, EMI, exams, documents) with poll stickers.",
  "1) Recognition session-wise verify hoti hai 2) Fees university ko jaati hai 3) EMI kai universities mein 4) Exams online (ODL mein centre ho sakta hai) 5) Documents soft copy, pehle verify. Aur sawaal? Reply karo.",
  "Reply with your question.", "ASK", "trust",
  "Vertical story: five Q&A cards on navy with gold numbers.",
  "Engagement (story)", LP["elig"], "Replies", "Sticker taps", ["ENGAGEMENT", "RETARGETING"], "FOLLOWER", ratio="9:16 story"),
d(80, P6, PA, "Retargeting Ad (Static)", "BA / B.Com", "Retargeting · Eligibility started, not submitted", "Retargeting / Lead", "BOFU", "Eligibility-form openers (14d)", "21–34", GEO_RT,
  "Eligibility check अधूरा रह गया — 1 minute में complete करो.",
  "PA-24 Retargeting 3/3. Audience: started form, did not submit.",
  "Aapne eligibility check shuru kiya tha. Bas naam aur number — aur advisor aapko bata dega kaunse graduation options open hain. Koi obligation nahi.",
  "Complete My Eligibility Check", "GRADUATION", "grad",
  "Half-filled form on a phone (abstract) with a gold arrow; Indian student's hand; navy.",
  "Leads (retargeting: form opened, not submitted 14d)", LP["grad"], "Cost per lead (retarget)", "Form completion rate", ["RETARGETING", "LEAD"], "CONVERSION"),
d(81, P6, PA, "Conversion Ad (Reel)", "General", "Conversion · Application started, incomplete", "Conversion", "BOFU", "Application started, no documents (CRM)", "18–40", GEO_RT,
  "Application बन गई है — documents upload बाकी हैं.",
  "PA-25 Conversion 2/3. CRM audience; reel showing the dashboard upload (abstract) + counsellor help.",
  "Aapki application ID ready hai. Sirf documents upload baaki hain — dashboard se 5 minute mein. Scan mein dikkat? Counsellor WhatsApp par help karega.",
  "Upload Documents", "DOCS", "trust",
  "Vertical: dashboard upload screen (abstract) on a laptop, gold progress bar; navy.",
  "Conversions (custom audience: applications without documents)", "/student/dashboard", "Documents submitted", "Application completion rate", ["APPLICATION", "RETARGETING"], "CONVERSION", ratio="9:16 vertical Reel"),
d(82, P6, PA, "Video Ad (Reel)", "General", "Awareness · Brand", "Awareness / Video views", "TOFU", "Lookalike of leads (1%)", "18–40", GEO_SCALE,
  "One platform. 26+ universities. Zero guesswork.",
  "PA-26 Awareness 5/6. Brand film 15-sec for lookalike audiences built from qualified leads.",
  "Explore, compare, check eligibility, apply, track — sab ek jagah, aur ek counsellor degree tak. Mumbai Institute for Online & Distance Learning ka student platform: DegreeComplete.in.",
  "Explore Universities", "HELLO", "trust",
  "Vertical brand montage: seal on white, Indian students and professionals in three settings, navy-gold typography.",
  "Video views (lookalike 1% of leads)", LP["uni"], "ThruPlay rate", "Cost per ThruPlay", ["REACH", "RETARGETING"], "CONVERSION", ratio="9:16 vertical Reel"),
d(83, P6, PA, "Traffic Ad (Static)", "General", "Traffic · Compare", "Traffic", "MOFU", "Engagers + visitors", "18–40", GEO_RT,
  "Apply करने से पहले options compare करो.",
  "PA-27 Traffic 4/4. Retarget engagers to /compare.",
  "4 programs side-by-side: eligibility, fees, duration, documents, EMI. Compare karo, phir decide karo — hum jaldi nahi karwate.",
  "Compare Universities", "COMPARE", "trust",
  "Comparison grid mock on a tablet, Indian student; navy-gold.",
  "Traffic (retargeting: engagers 30d)", LP["cmp"], "Landing page views", "Compare completed", ["WEBSITE TRAFFIC", "RETARGETING"], "LEAD"),
d(84, P6, PA, "Engagement Ad (Carousel)", "MBA", "Engagement · MBA myths", "Engagement", "TOFU", "Lookalike + engagers", "22–34", GEO_SCALE,
  "Online MBA के बारे में 5 myths.",
  "PA-28 Engagement 4/4. Myth/fact carousel for MBA; comment CTA.",
  "Myth: online MBA 'kam' hota hai / entrance zaroori / sirf IT walon ke liye / ek hi university sahi / fees hidden. Fact: degree university ki, most mein no entrance (SOURCE), any-discipline eligibility, fit-based choice, fees likhit mein.",
  "Comment MBA for the full guide.", "MBA", "mba",
  "Myth/Fact two-tone carousel cover with an Indian professional; navy-gold.",
  "Engagement (post)", LP["mba"], "Comments", "Saves", ["ENGAGEMENT", "RETARGETING"], "FOLLOWER"),
d(85, P6, PA, "Conversion Ad (Static)", "MBA", "Conversion · Apply", "Conversion", "BOFU", "MBA leads qualified, not applied", "22–34", GEO_RT,
  "आपका MBA program shortlist है — application शुरू करें?",
  "PA-29 Conversion 3/3. CRM audience of qualified MBA leads; CTA Apply Now.",
  "Counsellor ne eligibility aur fees confirm kar di hain. Ab application: 10 minute form, documents dashboard se, fees university ko. Intake dates ke liye counsellor se poochho (SOURCE: two intakes/year at most universities).",
  "Apply Now", "APPLY", "mba",
  "Indian professional signing on a tablet (abstract), gold pen; white desk, navy header.",
  "Conversions (custom audience: qualified MBA leads)", "/apply", "Application starts", "Cost per application", ["APPLICATION"], "CONVERSION"),
d(86, P6, PA, "Video Ad (Reel)", "BA / B.Com", "Awareness · Second chance", "Awareness / Video views", "TOFU", "Lookalike of graduation leads", "21–36", GEO_SCALE,
  "Second chance at graduation — from home.",
  "PA-30 Awareness 6/6. 12-sec brand-led graduation film for lookalikes.",
  "Jo chhoot gaya tha, woh ab possible hai. Online BA/B.Com — 12th pass eligibility, ghar se, job ke saath (SOURCE). Eligibility check free.",
  "See BA & B.Com options.", "GRADUATION", "grad",
  "Vertical: Indian woman at dawn by a window with a laptop, calm resolve; navy grade, gold text.",
  "Video views (lookalike 1% of graduation leads)", LP["grad"], "ThruPlay rate", "Cost per ThruPlay", ["REACH", "RETARGETING"], "CONVERSION", ratio="9:16 vertical Reel"),
d(87, P6, O, "Reel", "General", "Retargeting (organic) · Still deciding", "Lead", "BOFU", "Followers", "18–40", GEO_ORGANIC,
  "'Baad mein karenge' — यही सबसे महंगी decision है.",
  "Organic soft-retarget reel: cost of delay is a lost intake cycle (two intakes/year — SOURCE), not fake scarcity.",
  "Most universities mein saal mein do intakes hote hain (SOURCE). Ek cycle miss ka matlab 6 mahine. Scarcity nahi, simple planning: aaj eligibility check, kal decision, is intake mein admission.",
  "Check My Eligibility — link in bio.", "ELIGIBLE", "gen",
  "Vertical: calendar flipping with two gold-marked intake months; Indian student; navy.",
  "—", LP["find"], "Leads", "Link clicks", ["LEAD", "RETARGETING"], "CONVERSION", ratio="9:16 vertical Reel"),
d(88, P6, O, "Carousel", "General", "Student journey", "Trust", "BOFU", "All", "18–40", GEO_ORGANIC,
  "Enquiry से LMS login तक — एक student का journey (steps).",
  "Anonymised process journey (no fake testimonial): the 8 steps with what the student did and what we did.",
  "Day 0 enquiry → same day counselling → documents pre-check → portal registration → fee/EMI → university verification (2–7 working days) → admission letter → LMS aur ABC ID (SOURCE). Har step par kaun kya karta hai, yeh clear ho toh dar nahi lagta.",
  "Start your journey — message START.", "START", "trust",
  "Eight-step journey path with gold nodes on white, Indian student silhouette at the end; navy header.",
  "—", LP["process"], "DMs", "Saves", ["WHATSAPP", "APPLICATION"], "CONVERSION"),
d(89, P6, O, "Static", "General", "Get current fee details", "Lead / WhatsApp", "BOFU", "All", "18–40", GEO_ORGANIC,
  "Current fee details चाहिए? University + course बताओ.",
  "WhatsApp-first lead post: send university + course → get written fee breakup and plans.",
  "Fees change hoti rehti hain — isliye hum current, likhit fee breakup dete hain: registration, exam, tuition, plans, EMI. University aur course WhatsApp karo.",
  "WhatsApp for Guidance: 98 33 07 44 76.", "FEES", "trust",
  "Phone with a WhatsApp-style fee message (abstract, no logo), Indian student's hand; navy-gold.",
  "—", LP["uni"], "WhatsApp conversations", "Leads", ["WHATSAPP", "LEAD"], "CONVERSION"),
d(90, P6, O, "Reel + Story set", "General", "90-day recap · Speak with an advisor", "Lead / Call", "BOFU", "All", "18–40", GEO_ORGANIC,
  "90 दिन, 90 posts — अब आपकी बारी.",
  "Recap reel of the most-saved content + story CTA set (call, WhatsApp, eligibility). Internal: publish the 90-day performance review the same day.",
  "Course, university, fees, eligibility, documents — 90 din mein humne sab kuch bina bikri ke samjhaya. Ab ek step aapka: advisor se baat karo. Sach, fees likhit mein, aur support degree tak.",
  "Speak with an Education Advisor — call 98 33 07 44 76.", "CALL", "trust",
  "Vertical montage of best carousel covers on navy, seal at end, gold headline.",
  "—", LP["home"], "Calls", "Leads", ["CALL", "WHATSAPP", "LEAD"], "CONVERSION", ratio="9:16 vertical Reel", story="CTA stories: Call / WhatsApp / Eligibility link + 'Which post helped you most?' poll"),
]
assert len(DAYS) == 90 and [x["day"] for x in DAYS] == list(range(1, 91))
